### PR TITLE
adding GD dependencies to apt-get for image processing

### LINKED ISSUE #79: Dockerfile doesn't include Graphics Display library for handling images

### PR DESCRIPTION
**Pull request by CryptoGraffe**
This is required for uploading avatars and doing resizing. Fixes #79

### CODE REVIEW

**Review by crabsinger — COMMENTED** [review]
@CryptoGraffe I tried to run this locally but it errored. I needed to add a context block to the nginx in the docker-compose. Doesn't seem related to your change though...

```
index dec9f8c..3c87ab5 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -36,6 +36,7 @@ services:
   nginx:
     container_name: nginx
     build:
+      context: .
       dockerfile: Dockerfile-nginx
       args:
         # override the defaults in the dockerfile here
```

**Comment by CryptoGraffe** [comment]
@crabsinger that's fun.... I can add that in with this same PR

**Comment by CryptoGraffe** [comment]
@crabsinger added it

**Review by crabsinger — APPROVED** [review]
LGTM works now to run up and down.

**Pull request merged**
